#!/bin/bash

# Color Migration Sed Script
# Generated: 2025-12-13T22:32:17.086Z

# WARNING: Review each replacement carefully before running!
# Some colors may be intentionally hardcoded (e.g., brand colors in stories)

# Usage: ./migrate-colors.sh

set -e

# Tailwind background class replacements
echo "Replacing bg-[#hex] patterns..."
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F8F5F3\]/bg-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f8f5f3\]/bg-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FFFFFF\]/bg-sara-background-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ffffff\]/bg-sara-background-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#4CB6AC\]/bg-sara-accent/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#4cb6ac\]/bg-sara-accent/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E6F5F4\]/bg-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e6f5f4\]/bg-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#16273D\]/bg-sara-text-primary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#16273d\]/bg-sara-text-primary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#4B5D6E\]/bg-sara-text-secondary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#4b5d6e\]/bg-sara-text-secondary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6C778A\]/bg-sara-text-meta/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6c778a\]/bg-sara-text-meta/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E6E2DD\]/bg-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e6e2dd\]/bg-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F5F3F0\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f5f3f0\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#566273\]/bg-sara-text-secondary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E6E0D7\]/bg-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e6e0d7\]/bg-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E5F3F0\]/bg-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e5f3f0\]/bg-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#000000\]/bg-black/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#BBBBBB\]/bg-gray-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#bbbbbb\]/bg-gray-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#858585\]/bg-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#8D8D8D\]/bg-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#8d8d8d\]/bg-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#838383\]/bg-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#666666\]/bg-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#646464\]/bg-gray-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#D9D9D9\]/bg-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#d9d9d9\]/bg-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#DDDDE3\]/bg-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#dddde3\]/bg-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#C7C7C7\]/bg-gray-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#c7c7c7\]/bg-gray-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#8F8F8F\]/bg-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#8f8f8f\]/bg-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6F6F6F\]/bg-gray-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6f6f6f\]/bg-gray-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#303030\]/bg-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#171717\]/bg-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#1F2937\]/bg-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#1f2937\]/bg-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E5E5E5\]/bg-gray-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e5e5e5\]/bg-gray-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F5F5F5\]/bg-gray-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f5f5f5\]/bg-gray-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E54666\]/bg-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e54666\]/bg-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#B54747\]/bg-red-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#b54747\]/bg-red-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#9F3A3A\]/bg-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#9f3a3a\]/bg-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#8A3B3B\]/bg-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#8a3b3b\]/bg-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E13D45\]/bg-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e13d45\]/bg-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#D84356\]/bg-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#d84356\]/bg-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#A53326\]/bg-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#a53326\]/bg-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#EF4444\]/bg-red-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ef4444\]/bg-red-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#7F1D1D\]/bg-red-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#7f1d1d\]/bg-red-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#880000\]/bg-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#28AD21\]/bg-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#28ad21\]/bg-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#02BC02\]/bg-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#02bc02\]/bg-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#10B981\]/bg-green-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#10b981\]/bg-green-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#12A594\]/bg-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#12a594\]/bg-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0F9C9C\]/bg-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0f9c9c\]/bg-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#1F7F75\]/bg-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#1f7f75\]/bg-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0F4D49\]/bg-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0f4d49\]/bg-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0C7D7D\]/bg-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0c7d7d\]/bg-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0E857F\]/bg-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0e857f\]/bg-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0F8B8D\]/bg-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0f8b8d\]/bg-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#14B8A6\]/bg-teal-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#14b8a6\]/bg-teal-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0D9B8A\]/bg-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0d9b8a\]/bg-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#2F7A6D\]/bg-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#2f7a6d\]/bg-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#1E7068\]/bg-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#1e7068\]/bg-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6F8A86\]/bg-sage-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6f8a86\]/bg-sage-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#49605C\]/bg-sage-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#49605c\]/bg-sage-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FFC53D\]/bg-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ffc53d\]/bg-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FFBA1A\]/bg-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ffba1a\]/bg-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F6A609\]/bg-amber-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f6a609\]/bg-amber-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F59E0B\]/bg-amber-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f59e0b\]/bg-amber-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ED8A5C\]/bg-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ed8a5c\]/bg-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F97316\]/bg-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f97316\]/bg-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#8A5A2E\]/bg-brown-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#8a5a2e\]/bg-brown-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#9F4E2F\]/bg-brown-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#9f4e2f\]/bg-brown-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0081F1\]/bg-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#0081f1\]/bg-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#086DE0\]/bg-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#086de0\]/bg-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#3E63DD\]/bg-indigo-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#3e63dd\]/bg-indigo-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#2781F6\]/bg-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#2781f6\]/bg-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#1F93FF\]/bg-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#1f93ff\]/bg-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#3B82F6\]/bg-blue-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#3b82f6\]/bg-blue-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#229ED9\]/bg-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#229ed9\]/bg-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#2AABEE\]/bg-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#2aabee\]/bg-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#3B4770\]/bg-indigo-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#3b4770\]/bg-indigo-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6E56CF\]/bg-violet-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6e56cf\]/bg-violet-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#8B5CF6\]/bg-violet-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#8b5cf6\]/bg-violet-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#3E3A92\]/bg-iris-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#3e3a92\]/bg-iris-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E592A3\]/bg-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e592a3\]/bg-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#EC4899\]/bg-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ec4899\]/bg-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#CCE6DE\]/bg-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#cce6de\]/bg-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#C2E4DE\]/bg-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#c2e4de\]/bg-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#D3E8E2\]/bg-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#d3e8e2\]/bg-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#C4DAD6\]/bg-teal-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#c4dad6\]/bg-teal-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#D3E4E1\]/bg-teal-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#d3e4e1\]/bg-teal-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#EEF7F5\]/bg-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#eef7f5\]/bg-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F1F6F5\]/bg-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f1f6f5\]/bg-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E4F3F0\]/bg-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e4f3f0\]/bg-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E3F2EF\]/bg-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e3f2ef\]/bg-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E7F4F2\]/bg-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e7f4f2\]/bg-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#DFF4F0\]/bg-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#dff4f0\]/bg-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E4EFEC\]/bg-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e4efec\]/bg-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F2FFFB\]/bg-mint-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f2fffb\]/bg-mint-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FDFBF9\]/bg-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#fdfbf9\]/bg-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F7F3EB\]/bg-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f7f3eb\]/bg-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F6F1EB\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f6f1eb\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F5EFEA\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f5efea\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F4EFE9\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f4efe9\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F3EEE7\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f3eee7\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F1ECE6\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f1ece6\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F1EBE4\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f1ebe4\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F1EAE1\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f1eae1\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#EFE8E0\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#efe8e0\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#EFE6DB\]/bg-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#efe6db\]/bg-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#EEE7E1\]/bg-sand-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#eee7e1\]/bg-sand-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#EDE5DA\]/bg-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ede5da\]/bg-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#EDEAE5\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#edeae5\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ECE7E1\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ece7e1\]/bg-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E9E2D9\]/bg-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e9e2d9\]/bg-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E7E2DD\]/bg-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e7e2dd\]/bg-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E7DED3\]/bg-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e7ded3\]/bg-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E3DCD2\]/bg-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e3dcd2\]/bg-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E1D9CF\]/bg-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e1d9cf\]/bg-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#DDD5CA\]/bg-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ddd5ca\]/bg-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#D8D1C9\]/bg-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#d8d1c9\]/bg-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#D6CEC4\]/bg-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#d6cec4\]/bg-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#D5CBC0\]/bg-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#d5cbc0\]/bg-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#C9C3BA\]/bg-sand-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#c9c3ba\]/bg-sand-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E2E6EB\]/bg-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e2e6eb\]/bg-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E1E4EA\]/bg-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e1e4ea\]/bg-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#D2D9E3\]/bg-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#d2d9e3\]/bg-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#C9D7E3\]/bg-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#c9d7e3\]/bg-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#9AA3B1\]/bg-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#9aa3b1\]/bg-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#7D8895\]/bg-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#7d8895\]/bg-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6F7A85\]/bg-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6f7a85\]/bg-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#3D4A5C\]/bg-slate-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#3d4a5c\]/bg-slate-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FFF8F0\]/bg-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#fff8f0\]/bg-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FFF1D6\]/bg-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#fff1d6\]/bg-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FFEBD6\]/bg-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ffebd6\]/bg-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FEF4E1\]/bg-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#fef4e1\]/bg-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F4DEBE\]/bg-amber-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f4debe\]/bg-amber-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FFE6E0\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#ffe6e0\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F8E6E6\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f8e6e6\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FDF3F3\]/bg-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#fdf3f3\]/bg-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FDEDEE\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#fdedee\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FDEBEC\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#fdebec\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FDEBEB\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#fdebeb\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#FBEFF0\]/bg-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#fbeff0\]/bg-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F8E8E8\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f8e8e8\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F8D7D7\]/bg-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f8d7d7\]/bg-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F5D9D9\]/bg-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f5d9d9\]/bg-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F4E0E2\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f4e0e2\]/bg-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F3B0B0\]/bg-red-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f3b0b0\]/bg-red-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F1D7D7\]/bg-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f1d7d7\]/bg-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E5E7F2\]/bg-violet-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e5e7f2\]/bg-violet-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#E5E3FC\]/bg-iris-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#e5e3fc\]/bg-iris-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#F2F5F9\]/bg-slate-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#f2f5f9\]/bg-slate-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#A8ABA9\]/bg-sage-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#a8aba9\]/bg-sage-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#7E808A\]/bg-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#7e808a\]/bg-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#60646C\]/bg-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#60646c\]/bg-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6AB4B6\]/bg-cyan-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#6ab4b6\]/bg-cyan-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#B4BFC6\]/bg-slate-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#b4bfc6\]/bg-slate-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/bg-\[#800\]/bg-red-900/g' {} +

# Tailwind text class replacements
echo "Replacing text-[#hex] patterns..."
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F8F5F3\]/text-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f8f5f3\]/text-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FFFFFF\]/text-sara-background-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ffffff\]/text-sara-background-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#4CB6AC\]/text-sara-accent/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#4cb6ac\]/text-sara-accent/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E6F5F4\]/text-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e6f5f4\]/text-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#16273D\]/text-sara-text-primary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#16273d\]/text-sara-text-primary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#4B5D6E\]/text-sara-text-secondary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#4b5d6e\]/text-sara-text-secondary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6C778A\]/text-sara-text-meta/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6c778a\]/text-sara-text-meta/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E6E2DD\]/text-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e6e2dd\]/text-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F5F3F0\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f5f3f0\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#566273\]/text-sara-text-secondary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E6E0D7\]/text-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e6e0d7\]/text-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E5F3F0\]/text-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e5f3f0\]/text-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#000000\]/text-black/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#BBBBBB\]/text-gray-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#bbbbbb\]/text-gray-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#858585\]/text-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#8D8D8D\]/text-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#8d8d8d\]/text-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#838383\]/text-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#666666\]/text-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#646464\]/text-gray-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#D9D9D9\]/text-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#d9d9d9\]/text-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#DDDDE3\]/text-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#dddde3\]/text-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#C7C7C7\]/text-gray-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#c7c7c7\]/text-gray-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#8F8F8F\]/text-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#8f8f8f\]/text-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6F6F6F\]/text-gray-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6f6f6f\]/text-gray-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#303030\]/text-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#171717\]/text-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#1F2937\]/text-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#1f2937\]/text-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E5E5E5\]/text-gray-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e5e5e5\]/text-gray-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F5F5F5\]/text-gray-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f5f5f5\]/text-gray-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E54666\]/text-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e54666\]/text-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#B54747\]/text-red-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#b54747\]/text-red-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#9F3A3A\]/text-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#9f3a3a\]/text-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#8A3B3B\]/text-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#8a3b3b\]/text-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E13D45\]/text-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e13d45\]/text-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#D84356\]/text-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#d84356\]/text-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#A53326\]/text-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#a53326\]/text-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#EF4444\]/text-red-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ef4444\]/text-red-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#7F1D1D\]/text-red-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#7f1d1d\]/text-red-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#880000\]/text-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#28AD21\]/text-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#28ad21\]/text-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#02BC02\]/text-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#02bc02\]/text-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#10B981\]/text-green-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#10b981\]/text-green-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#12A594\]/text-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#12a594\]/text-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0F9C9C\]/text-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0f9c9c\]/text-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#1F7F75\]/text-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#1f7f75\]/text-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0F4D49\]/text-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0f4d49\]/text-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0C7D7D\]/text-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0c7d7d\]/text-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0E857F\]/text-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0e857f\]/text-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0F8B8D\]/text-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0f8b8d\]/text-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#14B8A6\]/text-teal-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#14b8a6\]/text-teal-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0D9B8A\]/text-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0d9b8a\]/text-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#2F7A6D\]/text-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#2f7a6d\]/text-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#1E7068\]/text-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#1e7068\]/text-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6F8A86\]/text-sage-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6f8a86\]/text-sage-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#49605C\]/text-sage-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#49605c\]/text-sage-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FFC53D\]/text-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ffc53d\]/text-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FFBA1A\]/text-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ffba1a\]/text-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F6A609\]/text-amber-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f6a609\]/text-amber-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F59E0B\]/text-amber-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f59e0b\]/text-amber-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ED8A5C\]/text-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ed8a5c\]/text-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F97316\]/text-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f97316\]/text-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#8A5A2E\]/text-brown-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#8a5a2e\]/text-brown-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#9F4E2F\]/text-brown-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#9f4e2f\]/text-brown-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0081F1\]/text-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#0081f1\]/text-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#086DE0\]/text-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#086de0\]/text-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#3E63DD\]/text-indigo-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#3e63dd\]/text-indigo-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#2781F6\]/text-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#2781f6\]/text-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#1F93FF\]/text-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#1f93ff\]/text-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#3B82F6\]/text-blue-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#3b82f6\]/text-blue-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#229ED9\]/text-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#229ed9\]/text-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#2AABEE\]/text-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#2aabee\]/text-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#3B4770\]/text-indigo-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#3b4770\]/text-indigo-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6E56CF\]/text-violet-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6e56cf\]/text-violet-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#8B5CF6\]/text-violet-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#8b5cf6\]/text-violet-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#3E3A92\]/text-iris-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#3e3a92\]/text-iris-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E592A3\]/text-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e592a3\]/text-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#EC4899\]/text-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ec4899\]/text-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#CCE6DE\]/text-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#cce6de\]/text-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#C2E4DE\]/text-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#c2e4de\]/text-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#D3E8E2\]/text-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#d3e8e2\]/text-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#C4DAD6\]/text-teal-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#c4dad6\]/text-teal-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#D3E4E1\]/text-teal-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#d3e4e1\]/text-teal-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#EEF7F5\]/text-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#eef7f5\]/text-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F1F6F5\]/text-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f1f6f5\]/text-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E4F3F0\]/text-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e4f3f0\]/text-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E3F2EF\]/text-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e3f2ef\]/text-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E7F4F2\]/text-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e7f4f2\]/text-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#DFF4F0\]/text-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#dff4f0\]/text-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E4EFEC\]/text-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e4efec\]/text-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F2FFFB\]/text-mint-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f2fffb\]/text-mint-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FDFBF9\]/text-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#fdfbf9\]/text-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F7F3EB\]/text-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f7f3eb\]/text-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F6F1EB\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f6f1eb\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F5EFEA\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f5efea\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F4EFE9\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f4efe9\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F3EEE7\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f3eee7\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F1ECE6\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f1ece6\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F1EBE4\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f1ebe4\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F1EAE1\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f1eae1\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#EFE8E0\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#efe8e0\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#EFE6DB\]/text-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#efe6db\]/text-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#EEE7E1\]/text-sand-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#eee7e1\]/text-sand-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#EDE5DA\]/text-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ede5da\]/text-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#EDEAE5\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#edeae5\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ECE7E1\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ece7e1\]/text-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E9E2D9\]/text-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e9e2d9\]/text-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E7E2DD\]/text-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e7e2dd\]/text-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E7DED3\]/text-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e7ded3\]/text-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E3DCD2\]/text-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e3dcd2\]/text-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E1D9CF\]/text-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e1d9cf\]/text-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#DDD5CA\]/text-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ddd5ca\]/text-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#D8D1C9\]/text-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#d8d1c9\]/text-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#D6CEC4\]/text-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#d6cec4\]/text-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#D5CBC0\]/text-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#d5cbc0\]/text-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#C9C3BA\]/text-sand-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#c9c3ba\]/text-sand-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E2E6EB\]/text-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e2e6eb\]/text-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E1E4EA\]/text-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e1e4ea\]/text-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#D2D9E3\]/text-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#d2d9e3\]/text-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#C9D7E3\]/text-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#c9d7e3\]/text-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#9AA3B1\]/text-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#9aa3b1\]/text-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#7D8895\]/text-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#7d8895\]/text-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6F7A85\]/text-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6f7a85\]/text-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#3D4A5C\]/text-slate-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#3d4a5c\]/text-slate-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FFF8F0\]/text-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#fff8f0\]/text-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FFF1D6\]/text-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#fff1d6\]/text-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FFEBD6\]/text-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ffebd6\]/text-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FEF4E1\]/text-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#fef4e1\]/text-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F4DEBE\]/text-amber-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f4debe\]/text-amber-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FFE6E0\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#ffe6e0\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F8E6E6\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f8e6e6\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FDF3F3\]/text-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#fdf3f3\]/text-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FDEDEE\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#fdedee\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FDEBEC\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#fdebec\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FDEBEB\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#fdebeb\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#FBEFF0\]/text-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#fbeff0\]/text-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F8E8E8\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f8e8e8\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F8D7D7\]/text-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f8d7d7\]/text-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F5D9D9\]/text-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f5d9d9\]/text-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F4E0E2\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f4e0e2\]/text-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F3B0B0\]/text-red-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f3b0b0\]/text-red-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F1D7D7\]/text-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f1d7d7\]/text-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E5E7F2\]/text-violet-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e5e7f2\]/text-violet-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#E5E3FC\]/text-iris-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#e5e3fc\]/text-iris-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#F2F5F9\]/text-slate-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#f2f5f9\]/text-slate-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#A8ABA9\]/text-sage-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#a8aba9\]/text-sage-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#7E808A\]/text-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#7e808a\]/text-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#60646C\]/text-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#60646c\]/text-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6AB4B6\]/text-cyan-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#6ab4b6\]/text-cyan-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#B4BFC6\]/text-slate-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#b4bfc6\]/text-slate-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/text-\[#800\]/text-red-900/g' {} +

# Tailwind border class replacements
echo "Replacing border-[#hex] patterns..."
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F8F5F3\]/border-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f8f5f3\]/border-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FFFFFF\]/border-sara-background-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ffffff\]/border-sara-background-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#4CB6AC\]/border-sara-accent/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#4cb6ac\]/border-sara-accent/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E6F5F4\]/border-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e6f5f4\]/border-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#16273D\]/border-sara-text-primary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#16273d\]/border-sara-text-primary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#4B5D6E\]/border-sara-text-secondary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#4b5d6e\]/border-sara-text-secondary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6C778A\]/border-sara-text-meta/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6c778a\]/border-sara-text-meta/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E6E2DD\]/border-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e6e2dd\]/border-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F5F3F0\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f5f3f0\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#566273\]/border-sara-text-secondary/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E6E0D7\]/border-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e6e0d7\]/border-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E5F3F0\]/border-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e5f3f0\]/border-sara-accent-light/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#000000\]/border-black/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#BBBBBB\]/border-gray-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#bbbbbb\]/border-gray-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#858585\]/border-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#8D8D8D\]/border-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#8d8d8d\]/border-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#838383\]/border-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#666666\]/border-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#646464\]/border-gray-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#D9D9D9\]/border-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#d9d9d9\]/border-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#DDDDE3\]/border-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#dddde3\]/border-gray-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#C7C7C7\]/border-gray-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#c7c7c7\]/border-gray-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#8F8F8F\]/border-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#8f8f8f\]/border-gray-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6F6F6F\]/border-gray-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6f6f6f\]/border-gray-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#303030\]/border-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#171717\]/border-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#1F2937\]/border-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#1f2937\]/border-gray-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E5E5E5\]/border-gray-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e5e5e5\]/border-gray-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F5F5F5\]/border-gray-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f5f5f5\]/border-gray-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E54666\]/border-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e54666\]/border-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#B54747\]/border-red-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#b54747\]/border-red-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#9F3A3A\]/border-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#9f3a3a\]/border-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#8A3B3B\]/border-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#8a3b3b\]/border-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E13D45\]/border-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e13d45\]/border-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#D84356\]/border-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#d84356\]/border-red-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#A53326\]/border-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#a53326\]/border-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#EF4444\]/border-red-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ef4444\]/border-red-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#7F1D1D\]/border-red-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#7f1d1d\]/border-red-950/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#880000\]/border-red-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#28AD21\]/border-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#28ad21\]/border-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#02BC02\]/border-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#02bc02\]/border-green-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#10B981\]/border-green-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#10b981\]/border-green-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#12A594\]/border-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#12a594\]/border-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0F9C9C\]/border-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0f9c9c\]/border-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#1F7F75\]/border-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#1f7f75\]/border-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0F4D49\]/border-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0f4d49\]/border-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0C7D7D\]/border-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0c7d7d\]/border-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0E857F\]/border-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0e857f\]/border-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0F8B8D\]/border-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0f8b8d\]/border-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#14B8A6\]/border-teal-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#14b8a6\]/border-teal-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0D9B8A\]/border-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0d9b8a\]/border-teal-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#2F7A6D\]/border-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#2f7a6d\]/border-teal-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#1E7068\]/border-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#1e7068\]/border-teal-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6F8A86\]/border-sage-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6f8a86\]/border-sage-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#49605C\]/border-sage-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#49605c\]/border-sage-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FFC53D\]/border-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ffc53d\]/border-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FFBA1A\]/border-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ffba1a\]/border-amber-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F6A609\]/border-amber-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f6a609\]/border-amber-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F59E0B\]/border-amber-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f59e0b\]/border-amber-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ED8A5C\]/border-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ed8a5c\]/border-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F97316\]/border-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f97316\]/border-orange-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#8A5A2E\]/border-brown-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#8a5a2e\]/border-brown-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#9F4E2F\]/border-brown-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#9f4e2f\]/border-brown-800/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0081F1\]/border-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#0081f1\]/border-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#086DE0\]/border-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#086de0\]/border-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#3E63DD\]/border-indigo-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#3e63dd\]/border-indigo-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#2781F6\]/border-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#2781f6\]/border-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#1F93FF\]/border-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#1f93ff\]/border-blue-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#3B82F6\]/border-blue-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#3b82f6\]/border-blue-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#229ED9\]/border-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#229ed9\]/border-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#2AABEE\]/border-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#2aabee\]/border-sky-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#3B4770\]/border-indigo-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#3b4770\]/border-indigo-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6E56CF\]/border-violet-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6e56cf\]/border-violet-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#8B5CF6\]/border-violet-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#8b5cf6\]/border-violet-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#3E3A92\]/border-iris-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#3e3a92\]/border-iris-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E592A3\]/border-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e592a3\]/border-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#EC4899\]/border-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ec4899\]/border-pink-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#CCE6DE\]/border-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#cce6de\]/border-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#C2E4DE\]/border-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#c2e4de\]/border-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#D3E8E2\]/border-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#d3e8e2\]/border-jade-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#C4DAD6\]/border-teal-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#c4dad6\]/border-teal-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#D3E4E1\]/border-teal-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#d3e4e1\]/border-teal-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#EEF7F5\]/border-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#eef7f5\]/border-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F1F6F5\]/border-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f1f6f5\]/border-teal-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E4F3F0\]/border-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e4f3f0\]/border-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E3F2EF\]/border-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e3f2ef\]/border-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E7F4F2\]/border-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e7f4f2\]/border-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#DFF4F0\]/border-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#dff4f0\]/border-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E4EFEC\]/border-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e4efec\]/border-teal-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F2FFFB\]/border-mint-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f2fffb\]/border-mint-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FDFBF9\]/border-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#fdfbf9\]/border-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F7F3EB\]/border-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f7f3eb\]/border-sara-background/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F6F1EB\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f6f1eb\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F5EFEA\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f5efea\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F4EFE9\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f4efe9\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F3EEE7\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f3eee7\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F1ECE6\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f1ece6\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F1EBE4\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f1ebe4\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F1EAE1\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f1eae1\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#EFE8E0\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#efe8e0\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#EFE6DB\]/border-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#efe6db\]/border-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#EEE7E1\]/border-sand-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#eee7e1\]/border-sand-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#EDE5DA\]/border-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ede5da\]/border-sand-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#EDEAE5\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#edeae5\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ECE7E1\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ece7e1\]/border-sara-chip/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E9E2D9\]/border-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e9e2d9\]/border-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E7E2DD\]/border-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e7e2dd\]/border-sara-border/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E7DED3\]/border-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e7ded3\]/border-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E3DCD2\]/border-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e3dcd2\]/border-sand-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E1D9CF\]/border-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e1d9cf\]/border-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#DDD5CA\]/border-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ddd5ca\]/border-sand-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#D8D1C9\]/border-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#d8d1c9\]/border-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#D6CEC4\]/border-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#d6cec4\]/border-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#D5CBC0\]/border-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#d5cbc0\]/border-sand-500/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#C9C3BA\]/border-sand-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#c9c3ba\]/border-sand-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E2E6EB\]/border-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e2e6eb\]/border-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E1E4EA\]/border-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e1e4ea\]/border-slate-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#D2D9E3\]/border-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#d2d9e3\]/border-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#C9D7E3\]/border-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#c9d7e3\]/border-slate-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#9AA3B1\]/border-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#9aa3b1\]/border-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#7D8895\]/border-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#7d8895\]/border-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6F7A85\]/border-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6f7a85\]/border-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#3D4A5C\]/border-slate-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#3d4a5c\]/border-slate-900/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FFF8F0\]/border-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#fff8f0\]/border-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FFF1D6\]/border-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#fff1d6\]/border-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FFEBD6\]/border-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ffebd6\]/border-amber-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FEF4E1\]/border-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#fef4e1\]/border-amber-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F4DEBE\]/border-amber-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f4debe\]/border-amber-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FFE6E0\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#ffe6e0\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F8E6E6\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f8e6e6\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FDF3F3\]/border-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#fdf3f3\]/border-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FDEDEE\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#fdedee\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FDEBEC\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#fdebec\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FDEBEB\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#fdebeb\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#FBEFF0\]/border-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#fbeff0\]/border-red-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F8E8E8\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f8e8e8\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F8D7D7\]/border-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f8d7d7\]/border-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F5D9D9\]/border-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f5d9d9\]/border-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F4E0E2\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f4e0e2\]/border-red-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F3B0B0\]/border-red-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f3b0b0\]/border-red-300/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F1D7D7\]/border-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f1d7d7\]/border-red-200/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E5E7F2\]/border-violet-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e5e7f2\]/border-violet-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#E5E3FC\]/border-iris-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#e5e3fc\]/border-iris-100/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#F2F5F9\]/border-slate-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#f2f5f9\]/border-slate-50/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#A8ABA9\]/border-sage-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#a8aba9\]/border-sage-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#7E808A\]/border-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#7e808a\]/border-slate-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#60646C\]/border-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#60646c\]/border-slate-700/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6AB4B6\]/border-cyan-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#6ab4b6\]/border-cyan-600/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#B4BFC6\]/border-slate-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#b4bfc6\]/border-slate-400/g' {} +
find src -name "*.tsx" -exec sed -i '' 's/border-\[#800\]/border-red-900/g' {} +

echo "Color migration complete!"
echo "NOTE: SVG stroke/fill and inline color props need manual migration using tailwind.color()"